name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        name: Create Release
        with:
          release-type: simple
          changelog-types: |
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Patches", "hidden": false },
              { "type": "docs", "section": "Documentation", "hidden": false }
            ]
